### ISSUE TITLE
File : Open (startup) fails after running Help : Tutorial (tutor)

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#227]
Using either the newly created development database or Heroku.
Launch (or refresh) the system.  
Observe the PromptForDesign modal.
Select either Solid or Spring design model.
Load startup.
Optional: Confirm that File : Open (startup) works correctly.
Invoke menu item - Help : Tutorial (tutor)
Step through at least the first two pages of the tutorial; Cancel the remainder.
Invoke menu item - File : Open (startup) 
Observe the message: **"GET of 'initialState' design failed with message: 'Not Found' "**.

**Comment by grumpyinca** [comment]
The same problem also happens on Heroku.  Thus, it is probably NOT related to the new development database.

**Comment by 1fifoto** [comment]
Question: when you do the File Open in the problem case, did you just press the Open button, or did you first select 'startup' file name and then press the Open button. If you only pressed the Open button, then File Open assumes the default file name of the current model which in this case is 'initialState' and then fails because there isn't a file with that name. This is a known weakness of the Load InitialState capability.

**Comment by grumpyinca** [comment]
Yes, I see that this is exactly the problem and that this issue is a duplicate of issue #193.
