### ISSUE TITLE
Upgrade to @okta/okta-react to latest version AFTER 1.3.1

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#302]
This includes repairs to getting sign-out error message. Use "npm update". 

    Unhandled Rejection (AuthApiError): Not found: Resource not found: me (Session)
    ./node_modules/@okta/okta-auth-js/lib/errors/AuthApiError.js
    C:/Users/Mike/git/odop/client/node_modules/@okta/okta-auth-js/lib/errors/AuthApiError.js:26
    __webpack_require__
    C:/Users/Mike/git/odop/client/webpack/bootstrap:785

**Comment by grumpyinca** [comment]
@okta/okta-react version 1.4.0 was published Jan 30, 2020.

**Comment by 1fifoto** [comment]
Merged and closing

**Comment by grumpyinca** [comment]
I confirmed that this change has significantly improved the user experience of logout after the Okta session has expired.  Where previously, in the development environment, a trace-back was produced and the user was required to do a browser refresh in order to reach the sign-in page. With this change in place, the user gets to the sign-in page immediately ... the user's expected result.

In this situation, there is a message in red left in the console log:  "**dev-729070.okta.com/api/v1/sessions/me:1 DELETE https://dev-729070.okta.com/api/v1/sessions/me 404**".

We know that user experience results on this issue differ between development and production environments.  I will have to wait until this change is included in a release to Heroku to comment on behavior in that environment.
