### ISSUE TITLE
Fix stringify in File : Properties json creation

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#344]
The current use of stringify in File  : Properties creation of json is troubled.  Replace it with Base64 encode / decode.

Perhaps it would also be helpful to put error handling (throw / catch) around this process as another layer to prevent server crash.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by 1fifoto** [comment]
During File Save and Save As the JSON stringify operation converts ASCII x'0a' to '\n' characters. Unfortunately SQL then converts the '\n' back to x'0a'. During File Open the x'0a' causes JSON parse to fail. Instead we need to replace the stringify '\n' characters with '\\n' so that SQL does not convert it  treating it as '\n' and thus does not cause JSON parse to fail.
