### ISSUE TITLE
Optimize model access

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#363]
There are long-standing concerns that aspects of access to the model are not well optimized.  

For example:
  - the number of times that each design type's init.js is accessed
  - recalculation with each keystroke of input on the main page (a.k.a. Design)
  - issue #325 (Use Offset rather than string in init,js)
  - the number of times that dispatcher is invoked with various activities now that reset of Catalog Name/Number & Termination Condition have been implemented

These cases need to be investigated with regard to discovering opportunities for improvement.  If necessary. separate issues may be spun off to better isolate specific code changes.

**Comment by 1fifoto** [comment]
This is being used to optimize the model access by the React Components which use symbol_table entries. There are a number of React Components that need to be rendered because they connect to the symbol_table. However, low level, that is single entry in the symbol_table, React Components such as NameValueUnitsIndependentVariable should only need their entry and no other entries. To reduce the coupling on single entry components with the entire symbol_table code needs to be incorporated into the reducer & dispatcher to handle this coupling. For example, when a entry references a table with multiple column that need to set other entries the reducer & dispatcher must be modified to set the other entires. Similarly FDCL interdependencies presently pull the value from one entry into the current one. Instead the reducer & dispatcher need to do this cross-referencing and must change from pulling to pushing the value.

**Comment by 1fifoto** [comment]
Merged into master, closing
