### ISSUE TITLE
Migrate to latest version of Okta React

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#438]
See: https://www.npmjs.com/package/@okta/okta-react and "Migrating between versions" and its "Migrating from 1.x to 2.0". We are currently using 1.4. This is a breaking update and coding changes are needed.

**Comment by 1fifoto** [comment]
Initial work: Removed all of OKTA. Went back to what it was before Okta except set default user to 'public' user. Cleaned it in preparation for going forward and using the new okta-react.

**Comment by grumpyinca** [comment]
**First round of testing - notes & feedback**

1. When not signed-in (immediately after launch and also after Sign-Out) File : Open
  - Design type dropdown does not drop
  - No [ReadOnly] designs are listed for selection

Is it possible that I need to run "npm install" at the server level as well as client ?

2. When signed in, File : Open Spring/Compression shows Bri's test designs (aaa, bbb, fff, sss) not marked [ReadOnly] as well as the expected [ReadOnly] designs

3. In order to facilitate the use of Tutor & demo in testing, it would be helpful to have the latest fix to loadInitialState in branch 438.

**Comment by 1fifoto** [comment]
Per your request # 5 in "First round of testing - notes & feedback
![Screen Shot 2020-12-20 at 8 27 00 PM](https://user-images.githubusercontent.com/1581602/102733054-dc00cb80-4301-11eb-9142-4098614ea299.png)
" comment

**Comment by 1fifoto** [comment]
Per your request # 4 in "First round of testing - notes & feedback" comment I added into File Open the ability to LOad Initial State, Load Metric Initial State and Load Auto Save, because PromptForDesign no longer exists.
![Screen Shot 2020-12-20 at 9 14 48 PM](https://user-images.githubusercontent.com/1581602/102735564-6c420f00-4308-11eb-8ab3-2d9de430f543.png)

**Comment by grumpyinca** [comment]
**Second round of testing - notes & feedback**

When logged in, I am not seeing expected private designs that should be associated with my ID.  If I Save As a design, there is no error message, but a design with that name is not available for selection.

Testing will continue unless you suggest otherwise.

**Comment by 1fifoto** [comment]
Fixed # 1 and # 2 above. 
# 3 Let's talk about it on the weekend. That is, should the view be saved in the root of the model?
# 4 Yes, the public user is not assigned to the development environemnt.
# 5 See # 3. 
# 6 Should the exec / tutor / demo session be saved in the root of the model?

**Comment by grumpyinca** [comment]
**Reminder:**

Since it will be challenging to "back out" the changes of this branch after merging into master, it is likely to create a GitHub tag before doing the merge.  At least that will make it easy to identify the exact point of the merge.

**Comment by 1fifoto** [comment]
Merged into #388 and then master, closing
