### ISSUE TITLE
No default constraint value (cmin, cmax) if IV FIXed at initialization

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#440]
Steps to reproduce:

 - Open an extension spring design such as Startup or initialState.
 - Observe that End_Extension is FIXed.
 - FREE End_Extension
 - Click either constraint checkbox
 - Observe that there is no default constraint value (cmin, cmax); violation shows NaN%

Note that while this is technically a bug, it is essentially cosmetic.  Repair is not urgent.  There is no loss of data risk.  The user only needs to fill in appropriate values and proceed.

Preliminary investigation:

![image](https://user-images.githubusercontent.com/39974784/100533074-2f757300-31b5-11eb-9a6f-491b00d6679d.png)

![image](https://user-images.githubusercontent.com/39974784/100565074-88a5db00-3277-11eb-99ba-9f401bf12f73.png)

**Comment by 1fifoto** [comment]
I figured out what is wrong. When we set the FIXED flag we save the current constraint values and flags so that later when with un-FIXED it we can restore them. Since this flag was initialized in initialState the saved values and flags are not present. So when we try to restore them they are undefined. A migration is needed to retrofix all models with the save 'old' values.

**Comment by 1fifoto** [comment]
Also fixed a number of differences between IV and DV constraints for both min and max. I would like to walk through these with you to make sure that making them the same makes sense.

**Comment by 1fifoto** [comment]
Merged into master, closing
