### ISSUE TITLE
Make long hold to right click for context menu for iPad

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#484]

**Comment by grumpyinca** [comment]
From Slack:
Using the staging system, I am able to use a long press to bring up the Calculator mode context menu in both SurfacePro Windows 10 Tablet Mode and on my Android 7.1.1 phone.  In both cases, operation is less than 100% satisfactory (reliable, predictable, etc.).  Windows actually offers three different results depending on where you press in the cell (on digits versus on blank space to the left).

I did some web searching and got conflicting results.  I suspect that the correct answer depends on the version of iOS.

[Link to best article found so far](https://www.idownloadblog.com/2020/06/08/ipad-right-click-tutorial/)

Other articles suggest that in order to trigger a context menu, it is necessary to hold **5** seconds.

**Comment by grumpyinca** [comment]
Issue / Branch #577 makes this change moot.  Not implemented.  Closing.
