### ISSUE TITLE
Add standard size table for metric Outside Diameters

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#609]
Review various on-line catalogs to establish common metric coil outside diameters for compression, extension & torsion design types.  Create a standard size table.  Update (designtype)/sizes.js to utilize that table.

**Comment by 1fifoto** [comment]
* Rename file mat_ips.json to mat_us.json, and mat_SI.json to mat_metric.json. Similarly migrate Material_File value in initial_state.js to these new file names. 

* Rename mat_ips_offsets.js to mat_offsets.js throughout, because the offsets apply to both us (was ips) and metric (was SI) material tables. 

* Change column offset name in mat_offset from 'siznam' to 'wire_dia_filename'. In mat_us.json file change all row entries for this column from 'sizes*' to 'wire_dia_us'. In mat_metric.json file change all row entries for this column from 'sizes_met' to 'wire_dia_metric'. Rename all US wire diameter files from 'sizes*.json' to 'wire_dia_us*.json'. Rename Metric wire diameter file from 'sizes_met.json' to 'wire_dia_metric.json'.

* Add a new 'od_free_filename' column offset name in mat_offset immediately after 'wire_dia_filename' column offset name. In mat_us.json add row entries for this column as 'od_free_us.json'. Rename sizes_od_free.json file to od_free_us.json. In mat_us.json add row entries for this column as 'od_free_metric.json'. Create od_free_metric.json file and add title ["OD_Free"] and rows for standard Metric OD Free sizes..

**Comment by 1fifoto** [comment]
I have made and checked-in all the changes as specified in the above comment on [on Dec 25, 2021](https://github.com/thegrumpys/odop/issues/609#issuecomment-1001080312). The client designtype files are now renamed and organized as the following screen shot shows clearly separating materials, outside diameter and wire diameter.
<img width="201" alt="Screen Shot 2022-03-06 at 5 47 45 AM" src="https://user-images.githubusercontent.com/1581602/156921726-91f7951e-78b6-40b2-8d38-9328854ff637.png">

**Comment by 1fifoto** [comment]
Merged into master, closing
