### ISSUE TITLE
Reorganize offsets.js & symbol_table_offsets.js for all design types

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#624]
Reorganize / synchronize offsets.js & symbol_table_offsets.js for all design types including PCyl & Solid.

Delete System Controls (Preferences) and Labels (Properties) from offsets.js.  Confirm that the View menu code that generates the source table is working as desired.

**Comment by 1fifoto** [comment]
Did the following:

1. Remove System Controls (Preferences) and Labels (Properties) from ViewOffsets. 
2. No changes made to ViewSymbolTableOffsets, because they has already been made some time in the past. 
3. Ran ViewOffsets against all design types and created updated offset.js files. All design types offset.js files were affected.
4. Ran ViewSymbolTableOffsets against all design types and created updated symbol_table_offset.js files. Only Piston-Cylinder and Solid symbol_table_offset.js files were affected.

**Comment by 1fifoto** [comment]
Merged into master, closing
