### ISSUE TITLE
Add tooltip to dependent variable value

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#722]
Add tooltip to dependent variable value

Possible wording "To change the value of a Dependent Variable either FIX it or enable a MIN, a MAX or both constraints, and then set one or both of their values. This allows <img src="SearchButton.png" alt="SearchButton"/> to find the Dependent Variable's value that is within this constraint range."

**Comment by 1fifoto** [comment]
The inability to add tooltips to dependent variables is due to the addition of the alert's icon and its tooltip of alert messages. If the alert's icon and its tooltip is eliminated then the tooltip for dependent variables appears. See screen shot below.

![Screen Shot 2022-08-13 at 7 26 25 PM](https://user-images.githubusercontent.com/1581602/184517665-3a7c8a06-306d-4610-8ee9-74294f353108.png)

**Comment by 1fifoto** [comment]
Change to add text to Calculator view's pop to include the above help text.
![Screen Shot 2022-08-14 at 12 02 20 PM](https://user-images.githubusercontent.com/1581602/184547361-3af60bd6-4058-4c9f-bb7f-8cdb5383b80c.png)
Merged into master, closing
